# **Numpy-快速处理数据**

## 1. **概念**
* **Numpy**是高性能科学计算和数据分析的基础包。

2. 线性代数一个最明显的优势就是用矩阵乘法代替循环，可以极大地提高运算速度。

3. 最重要的一个特点是其N维数组对象（即**ndarray**），它是一个通用的同构数据多维容器，其中的**所有元素必须是相同类型的**，可以利用这种数组对整块数据执行一些数学运算。 

* **导入Numpy函数库**

In [140]:
import numpy as np

## 2. **数组基本操作**

### 2.1 创建数组

#### 2.11 直接创建

使用  <font color=DarkViolet>**array**函数</font>，接受的数据类型是<font color=DarkCyan>**list**</font>或者<font color=DarkCyan>**tuple**</font>

In [141]:
data1 = [6,7,8,9] #list

In [142]:
arr1 = np.array(data1)

In [143]:
arr1

array([6, 7, 8, 9])

In [144]:
data2 = (1,2,3,4) #tuple

In [145]:
arr2 = np.array(data2)

In [146]:
arr2

array([1, 2, 3, 4])

#### 2.12 快速创建 

In [147]:
a = np.arange(15).reshape(3,5) 
#reshape()方法可用来改变数组形状
#np.arange()的方式与python的range()类似，不同的是np.arange()支持小数的步长，而使用python的range时则会出错

In [148]:
a = np.arange(1,30,5)

In [149]:
a = np.arange(0,1,0.2)

In [150]:
a = np.linspace(0,np.e*10,5)

In [151]:
a = np.random.random((3,2))

In [152]:
a = np.zeros((3,4)) #对应维度的全零矩阵

In [153]:
a = np.ones((2,3,4),dtype = np.int64) #创建全1矩阵

In [154]:
a = np.empty((4,5))

### **2.2 查询数组的状态 **

In [155]:
a = np.arange(15).reshape(3,5)

In [156]:
a.ndim # 返回数组的秩

2

In [157]:
a.shape # 返回数组的形状

(3, 5)

In [158]:
a.dtype.name # 返回数组中数据的类型

'int32'

In [159]:
a.itemsize # 对象中每个元素的大小，以字节为单位

4

In [160]:
a.size # 数组中总共有多少个元素

15

### **2.3 改变数组的形状 **

In [305]:
a = np.random.random((3,4))

In [306]:
a

array([[ 0.20126006,  0.08960073,  0.46813963,  0.06777031],
       [ 0.47420195,  0.50385715,  0.75852914,  0.85872918],
       [ 0.28603204,  0.17944982,  0.06203664,  0.95512702]])

In [307]:
a.shape # 获得数组的形状

(3, 4)

#### 2.31 函数reshape 

In [309]:
a.reshape(2,6) # 可以改变数组形状，但不会改变原数组

array([[ 0.20126006,  0.08960073,  0.46813963,  0.06777031,  0.47420195,
         0.50385715],
       [ 0.75852914,  0.85872918,  0.28603204,  0.17944982,  0.06203664,
         0.95512702]])

In [312]:
a

array([[ 0.20126006,  0.08960073,  0.46813963,  0.06777031],
       [ 0.47420195,  0.50385715,  0.75852914,  0.85872918],
       [ 0.28603204,  0.17944982,  0.06203664,  0.95512702]])

#### 2.32 函数resize 

In [313]:
a.resize(2,6) # 可以改变数组形状，同时改变原数组

In [314]:
a

array([[ 0.20126006,  0.08960073,  0.46813963,  0.06777031,  0.47420195,
         0.50385715],
       [ 0.75852914,  0.85872918,  0.28603204,  0.17944982,  0.06203664,
         0.95512702]])

In [315]:
a.shape

(2, 6)

#### 2.33 用元组设置维度 

In [301]:
a.shape = (4,3) # 可直接用正整数元组来设置数组的维度，注意，这样会使得原数组发生改变

In [303]:
a

array([[ 0.70445283,  0.95430231,  0.4561827 ],
       [ 0.87936463,  0.34188148,  0.4215465 ],
       [ 0.68991614,  0.074094  ,  0.44336901],
       [ 0.48229716,  0.82128931,  0.1092687 ]])

#### 2.34 数组的展平

<font color=DarkViolet>**函数ravel**</font>--返回数组的一个视图

In [316]:
a = np.arange(12).reshape(2,6)

In [317]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [318]:
a.ravel() 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

<font color=DarkViolet>** 函数flatten** </font>--分配内存储存

In [319]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [322]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 2.35 数组的转置 

In [326]:
a = np.arange(12).reshape(6,2)

In [327]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [328]:
a.T # 转置

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [331]:
a.transpose() # 也可以写成这种形式

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

### **2.4 数组的复制 **

#### 2.41 完全不拷贝 

In [172]:
a = np.arange(12)
b = a
# 不会创建新的对象，即a和b是同一个ndarray对象的两个名字
# 也就是说如果对b改变形状或者改变数据，a也会发生相应的变化

In [173]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [174]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
b.resize(2,6)

In [176]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [177]:
a #原数组a由于b的形状的改变而改变

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [178]:
b[0][1] = 100

In [179]:
b

array([[  0, 100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [180]:
a #原数组a由于数组b的数据大小的改变而改变

array([[  0, 100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

#### 2.42 浅拷贝 

In [181]:
a = np.arange(12)
c = a.view()
# a的形状不会随着c的改变而发生改变，但是a的数据会随着c的改变而改变
# 换句话说，view()方法会创建一个共享数据的新的数组对象
# 如果数组A是数组B的视图，则称为B为A的base，视图数组中的数据实际上保存在base数组中

In [182]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [183]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [184]:
c[2] = 100

In [185]:
c

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [186]:
a #数组a的大小随着c的改变而改变

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [187]:
c.resize(2,6)

In [188]:
c

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [189]:
a #a数组的形状并没有随着c形状的改变而改变

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

#### 2.43 深拷贝 

In [190]:
a = np.arange(12)
d = a.copy()
# 创建了新的数组和新的数据
# 换句话说，改变数组d不会影响到原数组a

In [191]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [192]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [193]:
d[2] = 100

In [194]:
d

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [195]:
a #a的大小并没有随着d的改变而改变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [196]:
d.resize(2,6)

In [197]:
d

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [198]:
a #a的形状并没有随着d的改变而改变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### **2.5 数组的基本运算**

<font color=Crimson>**Numpy**</font>  数组运算的基本原则就是“按元素运算”

#### 2.51 加减法

In [199]:
a = np.array([10,20,30,40])

In [200]:
b = np.arange(4)

In [201]:
a

array([10, 20, 30, 40])

In [202]:
b

array([0, 1, 2, 3])

In [203]:
a - 4 # a中的所有元素都减去4

array([ 6, 16, 26, 36])

In [204]:
a - b # a中每个元素减去b中对应位置的元素

array([10, 19, 28, 37])

#### 2.52 乘法

In [205]:
a * b

array([  0,  20,  60, 120])

In [206]:
a.dot(b.T) #矩阵的点乘

200

### **2.6 常用函数 **

无论原始的数组是几维的，sum()、min()、max()函数都是将其当做一维的数组进行处理的

In [207]:
a = np.random.random((3,2))

In [208]:
a

array([[ 0.30672888,  0.81047387],
       [ 0.63973094,  0.55151222],
       [ 0.40550029,  0.0333495 ]])

In [209]:
a.sum()

2.7472956998109983

In [210]:
a.min()

0.033349504225572368

In [211]:
a.max()

0.81047386987608661

#### sum

计算数组元素之和

In [212]:
a.sum() #直接求和

2.7472956998109983

In [213]:
a.sum(axis=0) # 按照列的方向求和

array([ 1.35196011,  1.39533559])

In [214]:
a.sum(axis=1) # 按照行的方向求和

array([ 1.11720275,  1.19124316,  0.43884979])

#### np.sqrt 

计算数组元素的的平方根

In [215]:
a = np.arange(12).reshape(2,6)

In [216]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [217]:
b = np.sqrt(a)

In [218]:
b

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
         2.23606798],
       [ 2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
         3.31662479]])

#### np.ceil

对数组元素向上取整

In [219]:
a = np.random.randn(3,2)

In [220]:
a

array([[ 0.24679775,  0.73561753],
       [ 0.83091659, -0.17964493],
       [-0.3844243 , -1.76043784]])

In [221]:
np.ceil(a)

array([[ 1.,  1.],
       [ 1., -0.],
       [-0., -1.]])

####  np.modf

将数组各元素的小数和整数部分以两个独立数组形式返回

In [222]:
a = np.random.randn(4)

In [223]:
a

array([ 1.73868541, -1.12521604,  1.78132816, -0.25886645])

In [224]:
b = np.modf(a)

In [225]:
b #分成了两个数组

(array([ 0.73868541, -0.12521604,  0.78132816, -0.25886645]),
 array([ 1., -1.,  1., -0.]))

In [226]:
b[0] #分离得到小数部分

array([ 0.73868541, -0.12521604,  0.78132816, -0.25886645])

#### np.where

按条件返回数组的索引值

In [227]:
a = np.arange(12).reshape(3,4)

In [228]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
b = np.where(a > 7) 

In [230]:
b # 满足条件的索引值

(array([2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [231]:
a[b] # 按照索引得到的数组元素

array([ 8,  9, 10, 11])

#### np.take

从固定轴向的数组中取出指定元素

In [232]:
a = np.arange(12)

In [233]:
c = np.take(a,np.where(a>7)) # np.take 和 np.where 的综合使用

In [234]:
c

array([[ 8,  9, 10, 11]])

In [235]:
b = np.arange(12).reshape(3,4)

In [236]:
np.take(b,np.where(b>7)) # 不是一维数组的时候

array([[2, 2, 2, 2],
       [0, 1, 2, 3]])

In [237]:
c = np.ravel(b) # 是一维数组的时候

In [238]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [239]:
np.take(c,np.where(c>7))[0] # 貌似一维化后才可以按索引取值

array([ 8,  9, 10, 11])

#### ravel 和 flatten 

**两者所要实现的功能是一致的，即将数组展平成一维数组,默认是行序优先**

<font color=DarkViolet>**ravel( ) 函数**</font>

In [240]:
a = np.arange(12).reshape(3,4)

In [241]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [242]:
b = np.ravel(a) # np.ravel( ) 返回的是视图，对视图的修改是会影响到原数组的

In [243]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [244]:
c = a.ravel() # 也可以写成这种形式

In [245]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [246]:
a # 原数组还未发生变化

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [247]:
b[2] = 100

In [248]:
b # 修改视图的元素 

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [249]:
a # 原数组发生了变化

array([[  0,   1, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

<font color=DarkViolet>flatten( ) 函数</font>

In [250]:
a = np.arange(12).reshape(4,3)

In [251]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [252]:
b = a.flatten() # 写成np.flatten()的形式会报错

In [253]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [254]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [255]:
b[2] = 100

In [256]:
b # 改变拷贝的数据

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [257]:
a # 原数组不受影响

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### **2.7 数组的切片和索引 ** 

* python 是从0开始索引，数组的索引与列表的索引类似，这意味着数据不会被复制，任何修改都会直接反映到源数组上
* 理解多维数组：以2x3x4的三维数组为例，可以形象地把它看做一个两层楼建筑，每层楼有有12个房间，并排列成3行4列

In [282]:
a = np.arange(12).reshape(3,4)

In [283]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [284]:
a[2,-1] # [行向的位置，列向的位置] 支持负数下标，可以从尾部向前计数

11

In [285]:
a[::-1] # 利用负数下标翻转数组

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [289]:
b = np.arange(8)

In [279]:
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [281]:
b[::-1] # 注意一维数组和多维数组使用负数翻转的不一样

array([7, 6, 5, 4, 3, 2, 1, 0])

In [271]:
a[:,1:3] # 选取的数据范围：所有行，1到3之间的所有列（不包括第3列） 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [272]:
a[2,-1] = 100

In [273]:
a # 数据的修改直接反映到了源数组上

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 100]])

### **2.8 数组的组合**

In [336]:
a = np.random.random((2,3))
b = np.random.random((2,3))
c = np.random.random((2,3))
print('a','\n',a)
print('b','\n',b)
print('c','\n',c)

a 
 [[ 0.64329274  0.30829374  0.82777559]
 [ 0.97255359  0.75123731  0.39598394]]
b 
 [[ 0.57928867  0.02126319  0.7279046 ]
 [ 0.64662764  0.67442602  0.53551001]]
c 
 [[ 0.54023871  0.8907937   0.03209553]
 [ 0.47162738  0.00342755  0.79035865]]


#### 2.81 函数vstack 

垂直组合**vstack** -- 将ndarray对象构成的元组作为参数，传给vstack函数

In [348]:
np.vstack((a,b)) # 表示垂直堆叠，也就是竖方向拼接

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001]])

可以接收多个数组的拼接

In [359]:
np.vstack((a,b,c)) # 传入的参数需要是元组的形式

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001],
       [ 0.54023871,  0.8907937 ,  0.03209553],
       [ 0.47162738,  0.00342755,  0.79035865]])

vstack要求参与运算的多维数组在垂直方向上的个数必须相同，而水平方向的个数可以不同

In [356]:
d = np.random.random((4,3))

In [357]:
np.vstack((a,d))

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.6829977 ,  0.52758296,  0.25353949],
       [ 0.12268704,  0.90587187,  0.66381347],
       [ 0.46918394,  0.26360284,  0.87515732],
       [ 0.1639247 ,  0.36389539,  0.02201258]])

#### 2.82 函数hstack 

水平组合 **hstack** -- 将ndarray对象构成的**元组**作为参数，传给hstack函数

In [347]:
np.hstack((a,b)) # 表示水平堆叠，也就是横方向拼接

array([[ 0.64329274,  0.30829374,  0.82777559,  0.57928867,  0.02126319,
         0.7279046 ],
       [ 0.97255359,  0.75123731,  0.39598394,  0.64662764,  0.67442602,
         0.53551001]])

hstack要求参与运算的多维数组在水平方向上的个数必须相同，则垂直方向的个数可以不同

In [349]:
d = np.random.random((2,5))

In [351]:
d

array([[ 0.82651208,  0.36674849,  0.60407096,  0.36897867,  0.80416459],
       [ 0.75045923,  0.20772674,  0.36542817,  0.88236293,  0.1149964 ]])

In [353]:
result = np.hstack((a,d))

In [354]:
result

array([[ 0.64329274,  0.30829374,  0.82777559,  0.82651208,  0.36674849,
         0.60407096,  0.36897867,  0.80416459],
       [ 0.97255359,  0.75123731,  0.39598394,  0.75045923,  0.20772674,
         0.36542817,  0.88236293,  0.1149964 ]])

In [355]:
result.shape

(2, 8)

#### 2.83 函数concatenate

<font color=Crismon>推荐使用</font>

* 传入的参数必须是多个数组的<font color=DarkViolet>元组</font>
* 需指定拼接的方向：当axis=1的时候表示水平堆叠，当axis=0的时候表示垂直堆叠, 默认是axis=0

In [361]:
np.concatenate((a,b))

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001]])

In [362]:
np.concatenate((a,b),axis=0)

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001]])

In [363]:
np.concatenate((a,b),axis=1)

array([[ 0.64329274,  0.30829374,  0.82777559,  0.57928867,  0.02126319,
         0.7279046 ],
       [ 0.97255359,  0.75123731,  0.39598394,  0.64662764,  0.67442602,
         0.53551001]])

In [368]:
np.concatenate((a,b,c)) # 当然也可以拼接多个数组

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001],
       [ 0.54023871,  0.8907937 ,  0.03209553],
       [ 0.47162738,  0.00342755,  0.79035865]])

In [367]:
np.concatenate([a,b]) # 尝试了一下列表作为传入参数也可以，但是还是统一使用元组作为传入参数

array([[ 0.64329274,  0.30829374,  0.82777559],
       [ 0.97255359,  0.75123731,  0.39598394],
       [ 0.57928867,  0.02126319,  0.7279046 ],
       [ 0.64662764,  0.67442602,  0.53551001]])

#### 2.84 函数dstack 

所谓深度组合，就是将一系列数组沿着纵轴（深度）方向进行层叠组合

In [371]:
result = np.dstack((a,b))

In [372]:
result

array([[[ 0.64329274,  0.57928867],
        [ 0.30829374,  0.02126319],
        [ 0.82777559,  0.7279046 ]],

       [[ 0.97255359,  0.64662764],
        [ 0.75123731,  0.67442602],
        [ 0.39598394,  0.53551001]]])

In [373]:
result.shape

(2, 3, 2)

#### 2.85 函数column_stack

* 对于一维数组，将按列方向进行组合
* 对于二维数组，效果与hstack一致

In [374]:
c = np.arange(3)

In [375]:
c

array([0, 1, 2])

In [376]:
d = c * 2

In [377]:
d

array([0, 2, 4])

In [385]:
np.column_stack((c,d)) #  对于一维数组，按列方向进行组合

array([[0, 0],
       [1, 2],
       [2, 4]])

In [388]:
np.column_stack((a,b)) == np.hstack((a,b)) # 对于二维数组，两者效果是一样的

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

#### 2.86 函数row_stack 

* 对于两个一维数组，将直接层叠起来组合成一个二维数组
* 对于二维数组，效果与vstack一致

In [391]:
np.row_stack((c,d)) 

array([[0, 1, 2],
       [0, 2, 4]])

In [390]:
np.row_stack((a,b)) == np.vstack((a,b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

### **2.9 数组的分割 **

#### 2.91函数hsplit 

把数组沿着水平方向分割

In [392]:
a = np.arange(9).reshape(3,3)

In [393]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [395]:
b = np.hsplit(a,3)

In [396]:
b

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [398]:
b[0].shape

(3, 1)

#### 2.92 函数 vsplit

把数组沿着垂直方向分割

In [400]:
b = np.vsplit(a,3)

In [401]:
b

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [403]:
b[0].shape

(1, 3)

#### 2.93 函数split 

* 当axis=1时，相当于hsplit
* 当axis=0时，相当于vsplit

In [407]:
b = np.split(a,3,axis=1)

In [408]:
b

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [410]:
b[0].shape

(3, 1)

In [411]:
b = np.split(a,3,axis=0)

In [412]:
b

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [413]:
b[0].shape

(1, 3)

### 2.10 数组的转换 

<font color=DarkViolet> tolist函数 </font> 可以将Numpy 数组转换成 Python 列表

In [414]:
a = np.arange(4)

In [415]:
a

array([0, 1, 2, 3])

In [416]:
a.tolist()

[0, 1, 2, 3]

<font color=DarkViolet> astype函数 </font> 可以在转换数组时指定数据类型

In [417]:
a = np.arange(4)

In [418]:
a.dtype

dtype('int32')

In [421]:
b = a.astype(np.float)

In [422]:
b

array([ 0.,  1.,  2.,  3.])

In [423]:
b.dtype

dtype('float64')